### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by 2Craft** [DavidMGilbert/btc-hack-offline#3]
idk why but i get this error:

reading database files...
DONE
database size: 43212885
processes spawned: 24
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\EpicYT\Desktop\⠀⠀⠀⠀⠀⠀⠀\2xWallet\btc-hack-offline-main\btc-hack-offline-main\btc-hack-offline.py", line 66, in main
    public_key = private_key_to_public_key(private_key, args['fastecdsa'])
  File "C:\Users\EpicYT\Desktop\⠀⠀⠀⠀⠀⠀⠀\2xWallet\btc-hack-offline-main\btc-hack-offline-main\btc-hack-offline.py", line 26, in private_key_to_public_key
    pk = PrivateKey().fromString(bytes.fromhex(private_key))
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python39\lib\site-packages\ellipticcurve\privateKey.py", line 65, in fromString
    return PrivateKey(secret=intFromHex(string), curve=curve)
  File "C:\Users\EpicYT\AppData\Local\Programs\Python\Python39\lib\site-packages\ellipticcurve\utils\binary.py", line 13, in intFromHex
    return int(hexadecimal, 16)
ValueError: invalid literal for int() with base 16: b'p,!=s\x89Y\xdb\x0b\x0b\xf58\xb9\xa9\xc5}\xda\x97\x9f\x95\x83\xec\xfe:\x88\xba\xd1kg\xa72\x0e'

**Comment by aathemahesh** [comment]
Same error here should I use a Linux environment or windows is fine ?

**Comment by NightCorpse** [comment]
I believe it is necessary to be in a Linux environment

**Comment by NightCorpse** [comment]
I believe it is necessary to be in a Linux environment
